image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        name: Build
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew assembleDevelopmentDebug

  tags:
    release-*:
      - step:
          name: Generate release
          caches:
            - gradle
            - gradlewrapper
          script:
            - ./gradlew clean assembleProductionRelease -PSKELETON_STORE_PASSWORD=${SKELETON_STORE_PASSWORD} -PSKELETON_KEY_PASSWORD=${SKELETON_KEY_PASSWORD}
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"app/build/outputs/apk/production/release/skeleton-${BITBUCKET_TAG}.apk"

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper